---
- hosts: target
  become: yes
  remote_user: ec2-user
  become_user: root

  tasks:
  - name: create jenkins user on the server
    ansible.builtin.user:
      name: jenkins
      shell: /bin/bash
      createhome: yes

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Add repository
    ansible.builtin.yum_repository:
      name: epel repo
      description: EPEL YUM repo
      baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

  - name: install open-jdk-11
    command: amazon-linux-extras install java-openjdk11 -y

  - name: check Java is installed
    shell: 'java -version'
    register: java_version

  - debug:
      var: java_version.stdout

  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started

